sudo: true
language: cpp
compiler: gcc
env:
- CXXFLAGS="-std=gnu++11"
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
    env:
    - MATRIX_EVAL="CC=gcc && CXX=g++
  - os: osx
before_install: sudo apt-get install build-essential git cmake libboost-all-dev
install:
script: sudo make -j2
